### ISSUE TITLE
Add Contribution Agreement for all repos

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleOrg#4]

**Comment by pearswj** [comment]
There are some nice github integrations that will check if someone has signed the CLA and set the commit status on pull requests in the same way that AppVeyor does. I also wrote one that we never ended up using, but that was supposed to work across the whole organisation - https://github.com/mcneel/clam.

**Comment by didimitrie** [comment]
This sounds good! Though to be honest would love to have some insight on the text of the agreement itself, i'm literally a bit lost looking through stuff online!

**Comment by radumg** [comment]
I scoured the net for some good ones, settled on these bog-standard and super-basic templates for [contributing](https://github.com/radumg/DynaWeb/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/radumg/DynaWeb/blob/master/CODE_OF_CONDUCT.md) for some of my repos.

I would suggest the [Open Source Guide](https://opensource.guide/) as the best source for good advice and templates since the good folks (:clap:) that put it together have already done this legwork : 

- contributing guide : https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
- code of conduct :  https://opensource.guide/code-of-conduct/

Great idea on the PR/commit approval integration @pearswj , never seen this integrated into that before, would be most awesome.

**Comment by didimitrie** [comment]
Cheers, this looks good. But those are the easy ones :D i think what we're looking for is [a CLA](https://www.clahub.com/pages/why_cla) that would protect the IP of the project and allow a modicum of safety when you/others are contributing on **company** time...

**Comment by pearswj** [comment]
Just remembered one of the reasons that we never ended up rolling out CLAM... I think it's worth reading [this](https://www.joyent.com/blog/broadening-node-js-contributions), [this](https://nodejs.org/en/blog/uncategorized/notes-from-the-road/#easier-contribution) and [this](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11) before continuing down the CLA route.

**Comment by pearswj** [comment]
Does the last line of Node's "Developer's Certificate of Origin 1.1" (in `CONTRIBUTING.md`) provide enough IP protection?

>(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is **maintained indefinitely** and may be redistributed consistent with this project or the open source license(s) involved.

**Comment by didimitrie** [comment]
I believe so. Nice, cool refs. I believe the argument against CLAs > in favour. We'll stick to #3 and we can close this one...
