### ISSUE TITLE
Where Should We Keep docs? 

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleOrg#8]
Currently they're spread out on the website. I've taken that off the  main page as most of  the docs got outdated and i didn't have time to polish them up, and they ended up confusing users. 

There's also a beginning of a tutorial [here](https://github.com/speckleworks/SpeckleCore/wiki/Speckle-Plugin-Basics-with-the-.NET-SDK) on the speckle core wiki. 

The sublayer questions:
- what docs do we need?
- where do we want to keep them?
- how should we make sure we can update them fast and easy?

**Comment by radumg** [comment]
Whilst i like the format of the wiki & that it has revisions, I (or anyone else outside org team) can't contribute to it any more for example since the org permissions were changed.

I'd vote to go down the statically-generated site route, be it Jekyll or [VuePress ](https://github.com/vuejs/vuepress)(brand new , check it out😉 ). This way, maintenance of the docs could be crowd-sourced, PRs submitted whenever a bug is encountered, etc. Also, no messing around with servers or clunky & security nightmare-inducing CMSs.

The `SpeckleSpecs` docs site already shows this can produce a good-looking docs site 👏
